### ISSUE TITLE
Define message payloads for each stream

### ISSUE THREAD

**Issue by trisberg** [projectriff-demo/demo#11]
We now have two streams - cart-events and checkout-events.

We should define the payload content to use for each stream.

**Comment by markfisher** [comment]
We can make changes (and move it to this repo), but as a first pass, I was thinking we could connect to the cart-processor here: https://github.com/markfisher/cart-processor

So the stream should expect JSON that can be mapped into the corresponding event types defined there (CartEvent and CheckoutEvent).

**Comment by trisberg** [comment]
I think we have the payload types sorted now.
