### ISSUE TITLE
curl-data.sh assumes minikube or gke

### ISSUE THREAD

**Issue by jldec** [projectriff-demo/demo#3]
How about setting one "INGRESS" env-var for the whole demo script.

**Comment by jldec** [comment]
Sorry, I just noticed that there is support for both minikube and gke already - adjusted issue name - would still prefer using env-var for ingress if it exists.
 
```
if [ "$ns" = "" ]; then
  ingress=$(minikube ip)
else
  ingress=$(kubectl get svc/nginx-ingress-controller -n nginx-ingress -ojsonpath='{.status.loadBalancer.ingress[0].ip}')
fi
```

**Comment by jldec** [comment]
actually with the ingress config extracted, i'd suggest moving the remaining data load (one line?) out of this separate shell script and into the readme like the other steps.

**Comment by trisberg** [comment]
I can take care of this as part of #5

**Comment by jldec** [comment]
```
while read line; \
do curl ${ingress}/api/article \
  -H "Content-Type:application/json" \
  -H "Host: inventory-api.default.example.com" \
  -d "$line" ; \
done <data/sample-data.json
```

**Comment by trisberg** [comment]
Fixed vi https://github.com/projectriff-demo/demo/commit/c8eca4d5c7fdffb839346b01fbe46bd510972560
