### ISSUE TITLE
riff CLI does not yet support --container-port on "riff core deployer create"

### ISSUE THREAD

**Issue by jldec** [projectriff-demo/demo#6]
Should we move the apps to 8080?
 or 
merge https://github.com/projectriff/cli/pull/143 and publish a new release of the cli?

cc: @scothis

**Comment by trisberg** [comment]
I vote for merging PR

**Comment by scothis** [comment]
I vote for merging the PR, once the review is complete ;)

**Comment by trisberg** [comment]
Merged, updated the README to use `--target-port` flags
