### ISSUE TITLE
Do we even need the inventoty-gui app?

### ISSUE THREAD

**Issue by trisberg** [projectriff-demo/demo#7]
Seems to be unnecessary since we can access items via the storefront.

**Comment by trisberg** [comment]
@fbiville @jldec what do you think?

**Comment by jldec** [comment]
i agree

**Comment by fbiville** [comment]
The inventory GUI is a backoffice and allows to create/delete articles.
It is optional indeed, but not because of storefront, rather because of the inventory API.

**Comment by fbiville** [comment]
It may still be useful if we want to demo the effects article creation/deletion have on the riff streaming pipeline we demo (new ad suggested if a shiny new article is published...).

The demo would then only involve GUIs (inventory backoffice, storefront) and riff functions.
