### ISSUE TITLE
Create 2 streams with HTTP source

### ISSUE THREAD

**Issue by jldec** [projectriff-demo/demo#9]
First steps toward demo streaming: Create 2 streams with HTTP sources  

Suggest calling the 2 streams:
- cart-events
- checkout-events

and calling the HTTP source endpoint `events-api` with 2 paths matching the 2 streams.

cc: @markfisher

**Comment by markfisher** [comment]
are you planning to deploy the http-source as its own deployment, or as a sidecar with the storefront?

**Comment by jldec** [comment]
I would say start with separate deployments - designing the sidecar configuration without resorting to a lot of hardwiring feels more like an RFC rather than something we can do easily. I'm open to being corrected on that tho.

**Comment by markfisher** [comment]
Yes, we need an RFC for the _source-using-sidecar_ model, and that is definitely not a short term initiative, as it will most likely impact the current processor sidecar design as well. So, a separate deployment is fine. That said, we can at least colocate both stream endpoints on a single instance of the http-source just to have fewer moving parts for now.

**Comment by trisberg** [comment]
where is the http-source image that we can use?

Pulling this failed: `gcr.io/projectriff/http-source/github.com/projectriff/http-source/cmd` with "Failed to fetch "latest" from request"

Shouldn't have to look up the latest digest from the repo builds

Also mentioned here: https://github.com/projectriff/http-source/issues/8

**Comment by trisberg** [comment]
Added a start here: https://github.com/projectriff-demo/demo#the-shopping-streams

**Comment by jldec** [comment]
this is done :)
